# Generated by Django 3.0.11 on 2021-01-16 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='title',
            new_name='name',
        ),
    ]
